In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.shape

(768, 9)

In [ ]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:

x=df.iloc[:,:-1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
#splitting into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=42)
x_train

array([[  0.   , 162.   ,  76.   , ...,  53.2  ,   0.759,  25.   ],
       [  4.   , 146.   ,  78.   , ...,  38.5  ,   0.52 ,  67.   ],
       [  4.   , 184.   ,  78.   , ...,  37.   ,   0.264,  31.   ],
       ...,
       [ 10.   , 101.   ,  86.   , ...,  45.6  ,   1.136,  38.   ],
       [  0.   , 141.   ,   0.   , ...,  42.4  ,   0.205,  29.   ],
       [  0.   , 125.   ,  96.   , ...,  22.5  ,   0.262,  21.   ]])

In [ ]:
x_test

array([[6.00e+00, 9.80e+01, 5.80e+01, 3.30e+01, 1.90e+02, 3.40e+01,
        4.30e-01, 4.30e+01],
       [2.00e+00, 1.12e+02, 7.50e+01, 3.20e+01, 0.00e+00, 3.57e+01,
        1.48e-01, 2.10e+01],
       [2.00e+00, 1.08e+02, 6.40e+01, 0.00e+00, 0.00e+00, 3.08e+01,
        1.58e-01, 2.10e+01],
       [8.00e+00, 1.07e+02, 8.00e+01, 0.00e+00, 0.00e+00, 2.46e+01,
        8.56e-01, 3.40e+01],
       [7.00e+00, 1.36e+02, 9.00e+01, 0.00e+00, 0.00e+00, 2.99e+01,
        2.10e-01, 5.00e+01],
       [6.00e+00, 1.03e+02, 7.20e+01, 3.20e+01, 1.90e+02, 3.77e+01,
        3.24e-01, 5.50e+01],
       [1.00e+00, 7.10e+01, 4.80e+01, 1.80e+01, 7.60e+01, 2.04e+01,
        3.23e-01, 2.20e+01],
       [0.00e+00, 1.17e+02, 0.00e+00, 0.00e+00, 0.00e+00, 3.38e+01,
        9.32e-01, 4.40e+01],
       [4.00e+00, 1.54e+02, 7.20e+01, 2.90e+01, 1.26e+02, 3.13e+01,
        3.38e-01, 3.70e+01],
       [5.00e+00, 1.47e+02, 7.80e+01, 0.00e+00, 0.00e+00, 3.37e+01,
        2.18e-01, 6.50e+01],
       [1.00e+01, 1.11e+02, 7.00e+01, 2.70e+01, 0.00e+00, 2.75e+01,
        1.41e-01, 4.00e+01],
       [7.00e+00, 1.79e+02, 9.50e+01, 3.10e+01, 0.00e+00, 3.42e+01,
        1.64e-01, 6.00e+01],
       [4.00e+00, 1.48e+02, 6.00e+01, 2.70e+01, 3.18e+02, 3.09e+01,
        1.50e-01, 2.90e+01],
       [5.00e+00, 9.60e+01, 7.40e+01, 1.80e+01, 6.70e+01, 3.36e+01,
        9.97e-01, 4.30e+01],
       [2.00e+00, 8.80e+01, 5.80e+01, 2.60e+01, 1.60e+01, 2.84e+01,
        7.66e-01, 2.20e+01],
       [1.00e+00, 1.25e+02, 5.00e+01, 4.00e+01, 1.67e+02, 3.33e+01,
        9.62e-01, 2.80e+01],
       [3.00e+00, 8.40e+01, 7.20e+01, 3.20e+01, 0.00e+00, 3.72e+01,
        2.67e-01, 2.80e+01],
       [5.00e+00, 8.60e+01, 6.80e+01, 2.80e+01, 7.10e+01, 3.02e+01,
        3.64e-01, 2.40e+01],
       [4.00e+00, 1.83e+02, 0.00e+00, 0.00e+00, 0.00e+00, 2.84e+01,
        2.12e-01, 3.60e+01],
       [0.00e+00, 1.40e+02, 6.50e+01, 2.60e+01, 1.30e+02, 4.26e+01,
        4.31e-01, 2.40e+01],
       [5.00e+00, 1.04e+02, 7.40e+01, 0.00e+00, 0.00e+00, 2.88e+01,
        1.53e-01, 4.80e+01],
       [1.00e+00, 8.80e+01, 7.80e+01, 2.90e+01, 7.60e+01, 3.20e+01,
        3.65e-01, 2.90e+01],
       [1.30e+01, 1.06e+02, 7.20e+01, 5.40e+01, 0.00e+00, 3.66e+01,
        1.78e-01, 4.50e+01],
       [1.00e+00, 9.60e+01, 6.40e+01, 2.70e+01, 8.70e+01, 3.32e+01,
        2.89e-01, 2.10e+01],
       [1.00e+01, 1.29e+02, 7.60e+01, 2.80e+01, 1.22e+02, 3.59e+01,
        2.80e-01, 3.90e+01],
       [7.00e+00, 1.84e+02, 8.40e+01, 3.30e+01, 0.00e+00, 3.55e+01,
        3.55e-01, 4.10e+01],
       [6.00e+00, 1.09e+02, 6.00e+01, 2.70e+01, 0.00e+00, 2.50e+01,
        2.06e-01, 2.70e+01],
       [1.00e+00, 1.00e+02, 7.40e+01, 1.20e+01, 4.60e+01, 1.95e+01,
        1.49e-01, 2.80e+01],
       [2.00e+00, 1.02e+02, 8.60e+01, 3.60e+01, 1.20e+02, 4.55e+01,
        1.27e-01, 2.30e+01],
       [3.00e+00, 8.90e+01, 7.40e+01, 1.60e+01, 8.50e+01, 3.04e+01,
        5.51e-01, 3.80e+01]])

In [ ]:
y_train

NameError: name 'y_train' is not defined

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
#normalisation
#standardScalar
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(x_train)
X_train_nor=ss.transform(x_train)
X_test_nor=ss.transform(x_test)
X_train_nor

array([[-1.13361128,  1.27782336,  0.35178129, ...,  2.66397899,
         0.84969947, -0.69448615],
       [ 0.05222164,  0.77835173,  0.45550266, ...,  0.81752952,
         0.1318716 ,  2.88487745],
       [ 0.05222164,  1.96459683,  0.45550266, ...,  0.62911631,
        -0.63701515, -0.18314849],
       ...,
       [ 1.83097102, -0.6264122 ,  0.87038815, ...,  1.70935206,
         1.98200535,  0.41341211],
       [-1.13361128,  0.62226685, -3.58963082, ...,  1.30740387,
        -0.81421952, -0.35359438],
       [-1.13361128,  0.12279523,  1.38899501, ..., -1.1922114 ,
        -0.64302208, -1.03537792]])

In [ ]:
X_test_nor

array([[ 6.45138099e-01, -7.20063126e-01, -5.81711052e-01,
         7.82447153e-01,  9.41036285e-01,  2.52289886e-01,
        -1.38440150e-01,  8.39526822e-01],
       [-5.40694821e-01, -2.83025458e-01,  2.99920605e-01,
         7.19973281e-01, -6.91610031e-01,  4.65824859e-01,
        -9.85416965e-01, -1.03537792e+00],
       [-5.40694821e-01, -4.07893363e-01, -2.70546938e-01,
        -1.27919062e+00, -6.91610031e-01, -1.49658299e-01,
        -9.55382326e-01, -1.03537792e+00],
       [ 1.23805456e+00, -4.39110340e-01,  5.59224034e-01,
        -1.27919062e+00, -6.91610031e-01, -9.28432907e-01,
         1.14103546e+00,  7.25203362e-02],
       [ 9.41596329e-01,  4.66181972e-01,  1.07783089e+00,
        -1.27919062e+00, -6.91610031e-01, -2.62706226e-01,
        -7.99202204e-01,  1.43608742e+00],
       [ 6.45138099e-01, -5.63978245e-01,  1.44338548e-01,
         7.19973281e-01,  9.41036285e-01,  7.17042474e-01,
        -4.56807322e-01,  1.86220214e+00],
       [-8.37153051e-01, -1.56292149e+00, -1.10031791e+00,
        -1.54660927e-01, -3.85515044e-02, -1.45598990e+00,
        -4.59810786e-01, -9.50154978e-01],
       [-1.13361128e+00, -1.26940577e-01, -3.58963082e+00,
        -1.27919062e+00, -6.91610031e-01,  2.27168124e-01,
         1.36929872e+00,  9.24749764e-01],
       [ 5.22216394e-02,  1.02808755e+00,  1.44338548e-01,
         5.32551665e-01,  3.91092263e-01, -8.68538951e-02,
        -4.14758827e-01,  3.28189165e-01],
       [ 3.48679869e-01,  8.09568711e-01,  4.55502662e-01,
        -1.27919062e+00, -6.91610031e-01,  2.14607243e-01,
        -7.75174493e-01,  2.71443156e+00],
       [ 1.83097102e+00, -3.14242435e-01,  4.06171766e-02,
         4.07603921e-01, -6.91610031e-01, -5.64167365e-01,
        -1.00644121e+00,  5.83857993e-01],
       [ 9.41596329e-01,  1.80851195e+00,  1.33713432e+00,
         6.57499409e-01, -6.91610031e-01,  2.77411647e-01,
        -9.37361543e-01,  2.28831685e+00],
       [ 5.22216394e-02,  8.40785688e-01, -4.77989681e-01,
         4.07603921e-01,  2.04092433e+00, -1.37097418e-01,
        -9.79410037e-01, -3.53594378e-01],
       [ 3.48679869e-01, -7.82497079e-01,  2.48059919e-01,
        -1.54660927e-01, -1.15887383e-01,  2.02046363e-01,
         1.56452387e+00,  8.39526822e-01],
       [-5.40694821e-01, -1.03223289e+00, -5.81711052e-01,
         3.45130049e-01, -5.54124025e-01, -4.51119438e-01,
         8.70723714e-01, -9.50154978e-01],
       [-8.37153051e-01,  1.22795233e-01, -9.96596538e-01,
         1.21976426e+00,  7.43400152e-01,  1.64363720e-01,
         1.45940264e+00, -4.38817321e-01],
       [-2.44236591e-01, -1.15710079e+00,  1.44338548e-01,
         7.19973281e-01, -6.91610031e-01,  6.54238071e-01,
        -6.28004763e-01, -4.38817321e-01],
       [ 3.48679869e-01, -1.09466684e+00, -6.31041948e-02,
         4.70077793e-01, -8.15158812e-02, -2.25023584e-01,
        -3.36668766e-01, -7.79709092e-01],
       [ 5.22216394e-02,  1.93337986e+00, -3.58963082e+00,
        -1.27919062e+00, -6.91610031e-01, -4.51119438e-01,
        -7.93195277e-01,  2.42966222e-01],
       [-1.13361128e+00,  5.91049877e-01, -2.18686252e-01,
         3.45130049e-01,  4.25463764e-01,  1.33252563e+00,
        -1.35436686e-01, -7.79709092e-01],
       [ 3.48679869e-01, -5.32761269e-01,  2.48059919e-01,
        -1.27919062e+00, -6.91610031e-01, -4.00875914e-01,
        -9.70399646e-01,  1.26564154e+00],
       [-8.37153051e-01, -1.03223289e+00,  4.55502662e-01,
         5.32551665e-01, -3.85515044e-02,  1.07227031e-03,
        -3.33665303e-01, -3.53594378e-01],
       [ 2.72034571e+00, -4.70327316e-01,  1.44338548e-01,
         2.09439847e+00, -6.91610031e-01,  5.78872786e-01,
        -8.95313049e-01,  1.00997271e+00],
       [-8.37153051e-01, -7.82497079e-01, -2.70546938e-01,
         4.07603921e-01,  5.59701244e-02,  1.51802840e-01,
        -5.61928558e-01, -1.03537792e+00],
       [ 1.83097102e+00,  2.47663138e-01,  3.51781291e-01,
         4.70077793e-01,  3.56720762e-01,  4.90946620e-01,
        -5.88959733e-01,  4.98635050e-01],
       [ 9.41596329e-01,  1.96459683e+00,  7.66666777e-01,
         7.82447153e-01, -6.91610031e-01,  4.40703097e-01,
        -3.63699941e-01,  6.69080936e-01],
       [ 6.45138099e-01, -3.76676387e-01, -4.77989681e-01,
         4.07603921e-01, -6.91610031e-01, -8.78189384e-01,
        -8.11216060e-01, -5.24040264e-01],
       [-8.37153051e-01, -6.57629174e-01,  2.48059919e-01,
        -5.29504159e-01, -2.96337765e-01, -1.56903783e+00,
        -9.82413501e-01, -4.38817321e-01],
       [-5.40694821e-01, -5.95195221e-01,  8.70388148e-01,
         9.69868769e-01,  3.39535011e-01,  1.69679117e+00,
        -1.04848971e+00, -8.64932035e-01],
       [-2.44236591e-01, -1.00101591e+00,  2.48059919e-01,
        -2.79608671e-01,  3.87843737e-02, -1.99901822e-01,
         2.24978980e-01,  4.13412107e-01]])

In [ ]:
#model creation
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier(n_neighbors=7)
knn1.fit(X_train_nor,y_train)
y_pred=knn1.predict(X_test_nor)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
#performsance evaluation
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.65      0.79      0.71        19
           1       0.43      0.27      0.33        11

    accuracy                           0.60        30
   macro avg       0.54      0.53      0.52        30
weighted avg       0.57      0.60      0.57        30

In [ ]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.6

In [ ]:
pred=knn1.predict(ss.transform([[6,148,72,35,0,33.6,0.627,50,]]))
pred

array([1])